### ISSUE TITLE
Adaptation to allow use of alternative data sources

### ISSUE THREAD

**Issue by halltony** [simonrolph/easily_missed#14]
I’m working with data from a bird recording system developed by the BTO called BirdTrack. I was wondering how difficult it would be to adapt this tool to accept a different data source to iNat?  I might be interested in submitting a pull request or developing a fork of this if it was seen as a reasonable thing to do.

**Comment by simonrolph** [comment]
Hi @halltony 

In theory it's totally doable. Main practical constraints are:

- Access to birdtrack data, whereas inat data is all open and accessible by API whereas birdtrack data isn't completely open although I presume there's an authenticated API somewhere out there. I think there's various data on the NBN atlas though.
- API endpoints, inat API has a geospatial query where I provide a lat/long and a radius which helps make the queries needed to make easily missed work, would depend if birdtrack data can be queried in the same way.
- Working with my messy code, not sure how well it is written as to how easy it will be to understand/modify! Might need a bit of a rewrite to set it up better for taking different data sources.

Hope that helps, please do provide any more details about what you're envisaging.

**Comment by halltony** [comment]
Thanks for your detailed reply Simon. The lack of APIs in BirdTrack is I think the crux of the problem. I know that BTO is considering these but I don’t think anything has been published yet. 

I’ll speak to my contacts at BTO and see if they have a planned deliver date for some APIs and can also suggest that they replicate the geospatial query provided by iNat. 

Thanks again

**Comment by halltony** [comment]
Thanks for your detailed reply Simon. The lack of APIs in BirdTrack is I think the crux of the problem. I know that BTO is considering these but I don’t think anything has been published yet. 

I’ll speak to my contacts at BTO and see if they have a planned deliver date for some APIs and can also suggest that they replicate the geospatial query provided by iNat. 

Thanks again
